using BookingSystem.Domain.Restaurants.ValueObjects;

namespace BookingSystem.Application.Features.Restaurants.Queries.GetRestaurantWorkingSchedule;

public record GetRestaurantWorkingScheduleResponse(IEnumerable<DayOfWeekSchedule> Schedules);