// <auto-generated />
using System;
using System.Collections.Generic;
using BookingSystem.Application.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookingSystem.Application.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookingSystem.Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("GuestCount")
                        .HasColumnType("integer")
                        .HasColumnName("guest_count");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_id");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TableNumber")
                        .HasColumnType("integer")
                        .HasColumnName("table_number");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TimeSlot", "BookingSystem.Domain.Bookings.Booking.TimeSlot#BookingTimeSlot", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("end_time");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("start_time");
                        });

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("GuestId")
                        .HasDatabaseName("ix_bookings_guest_id");

                    b.HasIndex("RestaurantId", "TableNumber")
                        .HasDatabaseName("ix_bookings_restaurant_id_table_number");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Domain.Bookings.CancellationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CanceledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("canceled_at");

                    b.Property<int>("Reason")
                        .HasColumnType("integer")
                        .HasColumnName("reason");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("WhoCancelledId")
                        .HasColumnType("uuid")
                        .HasColumnName("who_cancelled_id");

                    b.HasKey("Id")
                        .HasName("pk_cancellation_records");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ix_cancellation_records_booking_id");

                    b.HasIndex("WhoCancelledId")
                        .HasDatabaseName("ix_cancellation_records_who_cancelled_id");

                    b.ToTable("cancellation_records", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Domain.FavoriteRestaurants.FavoriteRestaurant", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.HasKey("UserId", "RestaurantId")
                        .HasName("pk_favorite_restaurants");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("ix_favorite_restaurants_restaurant_id");

                    b.ToTable("favorite_restaurants", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Domain.Restaurants.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("contact_phone_number");

                    b.Property<string>("Description")
                        .HasMaxLength(350)
                        .HasColumnType("character varying(350)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "BookingSystem.Domain.Restaurants.Restaurant.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ApartmentNumber")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("address_apartment_number");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_country");

                            b1.Property<string>("HouseNumber")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("address_house_number");

                            b1.Property<string>("State")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_state");

                            b1.Property<string>("Street")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_street");

                            b1.Property<string>("ZipCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("address_zip_code");
                        });

                    b.HasKey("Id")
                        .HasName("pk_restaurants");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_restaurants_owner_id");

                    b.ToTable("restaurants", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Domain.Restaurants.Table", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<int>("TableNumber")
                        .HasColumnType("integer")
                        .HasColumnName("table_number");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("RestaurantId", "TableNumber")
                        .HasName("pk_tables");

                    b.ToTable("tables", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Domain.Users.Manager", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("UserId")
                        .HasName("pk_managers");

                    b.ToTable("managers", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Domain.Users.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "RefreshToken", "BookingSystem.Domain.Users.Session.RefreshToken#RefreshToken", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("ExpiresAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("refresh_token_expires_at");

                            b1.Property<byte[]>("Token")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("bytea")
                                .HasColumnName("refresh_token_token");
                        });

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sessions_user_id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BlockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blocked_until");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blocked");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("last_name");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(144)
                        .HasColumnType("bytea")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phone_number");

                    b.Property<DateTimeOffset>("RegistrationDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_date_time");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone_number");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Domain.Bookings.Booking", b =>
                {
                    b.HasOne("BookingSystem.Domain.Users.User", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_users_guest_id");

                    b.HasOne("BookingSystem.Domain.Restaurants.Table", "Table")
                        .WithMany()
                        .HasForeignKey("RestaurantId", "TableNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_tables_restaurant_id_table_number");

                    b.Navigation("Guest");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("BookingSystem.Domain.Bookings.CancellationRecord", b =>
                {
                    b.HasOne("BookingSystem.Domain.Bookings.Booking", null)
                        .WithOne("CancellationRecord")
                        .HasForeignKey("BookingSystem.Domain.Bookings.CancellationRecord", "BookingId")
                        .HasConstraintName("fk_cancellation_records_bookings_booking_id");

                    b.HasOne("BookingSystem.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("WhoCancelledId")
                        .HasConstraintName("fk_cancellation_records_users_who_cancelled_id");
                });

            modelBuilder.Entity("BookingSystem.Domain.FavoriteRestaurants.FavoriteRestaurant", b =>
                {
                    b.HasOne("BookingSystem.Domain.Restaurants.Restaurant", null)
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorite_restaurants_restaurants_restaurant_id");

                    b.HasOne("BookingSystem.Domain.Users.User", null)
                        .WithMany("FavoriteRestaurants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorite_restaurants_users_user_id");
                });

            modelBuilder.Entity("BookingSystem.Domain.Restaurants.Restaurant", b =>
                {
                    b.HasOne("BookingSystem.Domain.Users.Manager", "Owner")
                        .WithMany("Restaurants")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_restaurants_managers_owner_id");

                    b.OwnsOne("BookingSystem.Domain.Restaurants.ValueObjects.WorkingSchedule", "WorkingSchedule", b1 =>
                        {
                            b1.Property<Guid>("RestaurantId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId")
                                .HasConstraintName("fk_restaurants_restaurants_id");

                            b1.OwnsMany("BookingSystem.Domain.Restaurants.ValueObjects.DayOfWeekSchedule", "DayOfWeekSchedules", b2 =>
                                {
                                    b2.Property<Guid>("restaurant_id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("restaurant_id");

                                    b2.Property<byte>("DayOfWeek")
                                        .HasColumnType("smallint")
                                        .HasColumnName("day_of_week");

                                    b2.Property<TimeOnly?>("ClosingTime")
                                        .HasColumnType("time without time zone")
                                        .HasColumnName("closing_time");

                                    b2.Property<bool>("IsClosed")
                                        .HasColumnType("boolean")
                                        .HasColumnName("is_closed");

                                    b2.Property<TimeOnly?>("OpeningTime")
                                        .HasColumnType("time without time zone")
                                        .HasColumnName("opening_time");

                                    b2.HasKey("restaurant_id", "DayOfWeek")
                                        .HasName("pk_restaurant_daily_schedules");

                                    b2.ToTable("restaurant_daily_schedules", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("restaurant_id")
                                        .HasConstraintName("fk_restaurant_daily_schedules_restaurants_restaurant_id");
                                });

                            b1.Navigation("DayOfWeekSchedules");
                        });

                    b.Navigation("Owner");

                    b.Navigation("WorkingSchedule");
                });

            modelBuilder.Entity("BookingSystem.Domain.Restaurants.Table", b =>
                {
                    b.HasOne("BookingSystem.Domain.Restaurants.Restaurant", "Restaurant")
                        .WithMany("Tables")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tables_restaurants_restaurant_id");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("BookingSystem.Domain.Users.Manager", b =>
                {
                    b.HasOne("BookingSystem.Domain.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("BookingSystem.Domain.Users.Manager", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_managers_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookingSystem.Domain.Users.Session", b =>
                {
                    b.HasOne("BookingSystem.Domain.Users.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookingSystem.Domain.Users.User", b =>
                {
                    b.OwnsOne("BookingSystem.Domain.Users.ValueObjects.Birthdate", "BirthDate", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("Value")
                                .HasColumnType("date")
                                .HasColumnName("birth_date");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("BirthDate")
                        .IsRequired();
                });

            modelBuilder.Entity("BookingSystem.Domain.Bookings.Booking", b =>
                {
                    b.Navigation("CancellationRecord");
                });

            modelBuilder.Entity("BookingSystem.Domain.Restaurants.Restaurant", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("BookingSystem.Domain.Users.Manager", b =>
                {
                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("BookingSystem.Domain.Users.User", b =>
                {
                    b.Navigation("FavoriteRestaurants");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
